name: Build and Deploy
run-name: Workflow run for ${{ github.ref }}
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      aws-deploy:
        type: boolean
        required: true
        default: false
jobs:
  build-api-service-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables based on tag postfix
        id: set-env
        run: |
          if [[ "${GITHUB_REF##*/}" == *"-GA" ]]; then
            echo "REACT_APP_ENV=develop" >> $GITHUB_ENV
            echo "BE_BASE_URL=${{ vars.DEV_BE_BASE_URL }}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == *"-RC" ]]; then
            echo "REACT_APP_ENV=production" >> $GITHUB_ENV
            echo "BE_BASE_URL=${{ vars.BE_BASE_URL }}" >> $GITHUB_ENV
          else
            echo "REACT_APP_ENV=development" >> $GITHUB_ENV
            echo "BE_BASE_URL=${{ vars.DEV_BE_BASE_URL }}" >> $GITHUB_ENV
          fi

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfilebuild
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/aml-authoring-tool:${{ github.ref_name }}
          build-args: |
            APP_ENV=${{ env.REACT_APP_ENV }}
            BE_BASE_URL=${{ env.BE_BASE_URL }}

